name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version: [5.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Lua
        uses: leafo/gh-actions-lua@master
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Set up Luarocks
        uses: leafo/gh-actions-luarocks@master

      - name: Install dependencies
        run: |
          luarocks install luacheck

      - name: Run tests
        run: luacheck .
